name: userCI-dev

on:
  push:
    branches:
      - dev
jobs:
  dev-branch:
    name: cr-pr
    runs-on: ubuntu-latest
    outputs:
      pr-num: "any time"
    steps:  
      - name: checkout root
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: set-outs
        run: echo "pr is life"
  approve:
    runs-on: ubuntu-latest
    name: approve-merge
    needs: [dev-branch]
    steps:
      - name: echos
        run: echo "output cr ${{ needs.dev-branch.outputs.pr-num }}"
      - name: pause
        run: sleep 5
   
